### ISSUE TITLE
[BUG] Can't start the app right after installing

### ISSUE THREAD

**Issue by greenozon** [Fadi002/de4py#12]
**Describe the bug**
Can't start the app right after installing

never ending scrambling strings are changing in the title and lots of CPU being consumed...

**To Reproduce**
1. Install the app using installer, version 1.0.8

**Expected behavior**
successful run of the tool

**Screenshots**
![image](https://github.com/Fadi002/de4py/assets/765343/363554f7-f1f8-4e3c-94b4-74350a66bdaa)

**Additional context**
Win7x64 SP1

**Comment by Fadi002** [comment]
Do you have chrome installed on your pc? or do you have something that uses port 5456 on your localhost or did you try to install it from the source code ? Because i used pyinstaller to compile the file from windows 10 machine so yeah

**Comment by greenozon** [comment]
Yes, Google Chrome 109
I installed it using install from release page

the port you asked for (BTW what is that?) is not used on my system - 

![image](https://github.com/Fadi002/de4py/assets/765343/64b796a2-b70b-4a8c-8c13-f1631f1d7e95)

the most strangest thing is that it is eating CPU and title is rapidly updating with some random string...
any ideas what htat might be?

**Comment by Fadi002** [comment]
> Yes, Google Chrome 109
> I installed it using install from release page
> 
> the port you asked for (BTW what is that?) is not used on my system - 
> 
> ![image](https://github.com/Fadi002/de4py/assets/765343/64b796a2-b70b-4a8c-8c13-f1631f1d7e95)
> 
> theq most strangest thing is that it is eating CPU and title is rapidly updating with some random string...
> any ideas what htat might be?
> 

Try to download it from the source code (the port for the browser GUI)

**Comment by greenozon** [comment]
I"m not able to run it from sources...

here is the try to install dependencies:
(working on Python 3.12)

![image](https://github.com/Fadi002/de4py/assets/765343/5684904a-b947-4447-b3b7-7522f9e9bb6e)

**Comment by Fadi002** [comment]
> I"m not able to run it from sources...
> 
> here is the try to install dependencies:
> (working on Python 3.12)
> 
> ![image](https://github.com/Fadi002/de4py/assets/765343/5684904a-b947-4447-b3b7-7522f9e9bb6e)
> 

As i said in the FAQ it doesn't support python 3.12 
python 3.12 is broken most libraries don't support it so yeah

**Comment by Fadi002** [comment]
Oh also i forgot to tell you the CPU usage issue is from the title changer you can fix it by remove while true from the title changer function in main.py i will fix that in the next update but for now try to install python 3.11 and install the requirements then run the tool it should work normally

**Comment by greenozon** [comment]
OK! thanks for letting me know regarding python 3.12

do you think there is some chance to upgrade to 3.12 or it is an issue of dependent packages

**Comment by greenozon** [comment]
Looks like py2exe is a show stopper in version 3.12...
it's old raised issue and details could be found over here
https://github.com/py2exe/py2exe/issues/191

**Comment by Fadi002** [comment]
3.12 has issues in a lot of libraries or at least the libraries that i always use so i just dont recommend it for now :)

**Comment by greenozon** [comment]
OK, the issue is I cant just reinstall .12 to .11... as I need the 1st one for other tasks
do you know if it's possible to have > 1 version under windows?

**Comment by Fadi002** [comment]
> OK, the issue is I cant just reinstall .12 to .11... as I need the 1st one for other tasks do you know if it's possible to have > 1 version under windows?

yeah just install py 3.11 over it and you should have 2 python versions you can use py -3.12 to use py 3.12 and py -3.11 to use py 3.11

**Comment by Fadi002** [comment]
close the issue because its inactive for 24 hours 👍
