### ISSUE TITLE
Dump strings error

### ISSUE THREAD

**Issue by Ibooted** [Fadi002/de4py#14]
Whenever I click on dump strings in the pyshell, it just throws this error:
File "<string>", line 2, in <module>
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 119-194: character maps to < undefined > (without the spaces at the start and end of the brackets)

Help is appreciated, thanks!

**Comment by Fadi002** [comment]
Hi, i think i know why it's because i forgot to add UTF-8 encode to the code in this line 
https://github.com/Fadi002/de4py/blob/main/dlls%2Fsource%2FDe4pyTools%2Fpyshell%2Fpyshell%2Fdllmain.cpp#L821
You can fix it and recompile the dll or just wait for the next update and it should be fixed

**Comment by Ibooted** [comment]
I’ll just wait for the new update to come out, thanks for the help

**Comment by Fadi002** [comment]
the update will take a long time maybe 1-2 weeks because im a bit busy + im adding new features so heres the dll just paste it in the dlls folder 
[pyshell.zip](https://github.com/Fadi002/de4py/files/15045670/pyshell.zip)
