### ISSUE TITLE
[FEAT.] Add proper CLI not just TUI

### ISSUE THREAD

**Issue by suphamster** [Fadi002/de4py#17]
To bulk process multiple files would be useful to have proper CLI with usage such as (I'm not good with Python so don't advice to use API please):
`proper_cli.py command_name input_file [output_file]
`
Then I would compile it to exe with pyinstaller/auto-py-to-exe and create batch file that processes all py scripts for me.
For now I need to input: 
```
main.py --cli
deobfuscator
file_path
start
```
Not saying that I need output to file not just print command so such TUI is kinda useless and currently better to use GUI unless proper CLI would be added. Thanks for de4py, please consider to improve it with my suggestion if possible.

**Comment by AdvDebug** [comment]
sorry but we will probably never add CLI to de4py as a decision i made with @Fadi002.
