### ISSUE TITLE
[FEAT.]Add pyarmor, BlankOBFv2, Pycloak, Carbon, regboss, Virtus, lambdifier, dauricum, white-obfuscate, Vare-Obfuscator2.0, pyshield, PyObfuscate, Py3-Variable, jargonaut and Py-Code-Obfuscator support

### ISSUE THREAD

**Issue by suphamster** [Fadi002/de4py#18]
https://github.com/dashingsoft/pyarmor (at least detection since it seems that v8+ is undecrypted yet)
https://github.com/Blank-c/BlankOBF/blob/v2/BlankOBFv2.py (btw I have "failed to dis marshal code" on v1 at samples\blankOBF.py)
https://github.com/addi00000/pycloak
https://github.com/0sir1ss/Carbon
https://github.com/Fadi002/regboss
https://github.com/synnkfps/Virtus
https://github.com/gio54321/lambdifier
https://github.com/nighty1338/dauricum
https://github.com/WH1T3-E4GL3/white-obfuscate
https://github.com/saintdaddy/Vare-Obfuscator2.0
https://github.com/0xe2d0/pyshield
https://github.com/ferlyafriliyan/PyObfuscate (not duplicate, it's another tool and not supported!)
https://github.com/ferlyafriliyan/Py3-Variable (https://github.com/ferlyafriliyan/Py3-Variable/issues/1 decryptor?)
https://github.com/mad-cat-lon/jargonaut
https://github.com/LiuYuancheng/Py-Code-Obfuscator/blob/main/src/pyObfuscator.py (contains decryption code)
P.S. Most of it contains example file(s). Please add at least mentioned obfuscators detection support and decryption where possible.

**Comment by AdvDebug** [comment]
both me and @Fadi002 are taking a break from working on the project, we are probably gonna be late on updates (or not release any updates at all until we feel like it again) but we will keep this improvements in mind.
