### ISSUE TITLE
Please Add An Option For Deobfuscating This New Obfuscator

### ISSUE THREAD

**Issue by UnrealNoodle** [Fadi002/de4py#5]
[obfuscator.zip](https://github.com/Fadi002/de4py/files/13760402/obfuscator.zip)

This is obfuscator is from one of a stealer

**Comment by UnrealNoodle** [comment]
I think it uses AES-GCM encryption because that is what is mentioned in the python file.

**Comment by Fadi002** [comment]
fr just replace exec with print and its done 💀
