### ISSUE TITLE
[BUG]ModuleNotFoundError: No module named 'bottle.ext.websocket'

### ISSUE THREAD

**Issue by ghost** [Fadi002/de4py#6]
ModuleNotFoundError: No module named 'bottle.ext.websocket'
i execute and this happends

**Comment by AdvDebug** [comment]
hey, please don't use python 3.12 as the module that uses this module (eel) doesn't work with it right now, try using python 3.11 for example.

also make sure you install the requirements from the "requirements.txt" file.

**Comment by Stilsky** [comment]
just to lyk, even if you managed to get eel to work, imp still doesnt support 3.12

**Comment by Fadi002** [comment]
> just to lyk, even if you managed to get eel to work, imp still doesnt support 3.12

It's not my problem it's an eel problem and he is not working on his module anymore 
These are some fixes:
https://stackoverflow.com/questions/77232001/python-eel-module-unable-to-use-import-bottle-ext-websocket-as-wbs-modulenotfoun

**Comment by ghost** [comment]
Oh ok tks
