### ISSUE TITLE
[BUG] When deobfuscating a python file it returns a error

### ISSUE THREAD

**Issue by GnecQ** [Fadi002/de4py#8]
When I tried to deobfuscate a python file

It returned "Error : can only concatenate str (not "Error") to str"

**Comment by Fadi002** [comment]
Dear buddy,
This is a list of possibilities as to why it gave you an error
1- the file is not a python
2 - the file is compiled (pyc) (de4py is not a decompiler)
3 - unsupported obfuscator
4 - the obfuscator dev updated his obfuscator
So can you send the file so I can check it out?
if you don't want to send it here you can upload it to my website https://de4py.000.pe

**Comment by Fadi002** [comment]
Closing the issue because there's no response
