### ISSUE TITLE
[FEAT.] Pyc Decompiler

### ISSUE THREAD

**Issue by KiExitDispatcher** [Fadi002/de4py#9]
will yall add something like pyc decompiler? it could be useful.

**Comment by Fadi002** [comment]
Theres already decompilers online like [pycdc](https://github.com/zrax/pycdc) and [uncompyle6](https://pypi.org/project/uncompyle6/)
For now im not planning to add pyc decompiler but maybe i will add it in future

**Comment by KiExitDispatcher** [comment]
yh that will be fine, this is great tool imo even tho i dont rly like python.. it would be awesome to have all in one with the pyc decompiler and i think many people would like it. anyways ty for quick response
